version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-1 s3 sync ./dist/ s3://codepipeline-us-east-1-535461359183/ --acl=public-read --delete
